#!/usr/bin/env python3
"""
build-family-redirects.py

Translate `latest_for_family.json` (emitted by render-to-dir.mjs) into
Caddy `redir` directives so that `/<owner>/<family>` resolves to the
most-recent dated child page.

Usage:
    python3 wiki-engine/tools/build-family-redirects.py \\
        --in   rendered/latest_for_family.json \\
        --owner paul-demo2 \\
        --out  rendered/family-redirects.caddy

Output is plain Caddy syntax that can be `import`-ed from the main
Caddyfile or pasted inline:

    @for_you path /paul-demo2/for-you /paul-demo2/for-you/
    redir @for_you /paul-demo2/for-you-2026-04-26{uri} 302

We use 302 (temporary) because the latest target rotates daily; a
301 would let browsers + CDNs cache the wrong landing page.

`<family>/<date>` resolves directly to the dated parent page (the
file already exists under the original slug); no redirect needed
for that path. The historical-by-date URL is the canonical form.
"""

import argparse
import json
import sys
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--in", dest="input", required=True, help="Path to latest_for_family.json")
    ap.add_argument("--owner", required=True, help="URL prefix owner segment, e.g. paul-demo2")
    ap.add_argument("--out", required=True, help="Where to write the Caddy redirect snippet")
    args = ap.parse_args()

    in_path = Path(args.input)
    out_path = Path(args.out)
    if not in_path.exists():
        print(f"warning: {in_path} not found, writing empty snippet", file=sys.stderr)
        out_path.write_text("# no families discovered\n")
        return 0

    data = json.loads(in_path.read_text())
    if not isinstance(data, dict) or not data:
        out_path.write_text("# empty family map\n")
        return 0

    lines = [
        "# Auto-generated by wiki-engine/tools/build-family-redirects.py.",
        "# DO NOT EDIT: regenerated whenever rendered/latest_for_family.json changes.",
        f"# Owner namespace: /{args.owner}/",
        "",
    ]
    owner = args.owner.strip("/")
    for family, info in sorted(data.items()):
        if not isinstance(info, dict) or "slug" not in info:
            continue
        slug = info["slug"]
        date = info.get("date", "")
        matcher = f"@latest_{family.replace('-', '_')}"
        # Match both /<owner>/<family> and /<owner>/<family>/ (trailing slash).
        lines.append(f"{matcher} path /{owner}/{family} /{owner}/{family}/")
        # Redirect to the dated parent page. We do NOT preserve {uri} —
        # the family bare URL is treated as a request for "today's
        # snapshot" only, not as a reroute for sub-paths. Sub-paths
        # like /paul-demo2/for-you/2026-04-26/2026-04-25 should resolve
        # to the literal file at .../for-you-2026-04-26/2026-04-25.html
        # which is a separate concern (handled by Caddy's static handler).
        lines.append(f"redir {matcher} /{owner}/{slug} 302")
        lines.append(f"# {family} → {slug} (latest as of {date})")
        lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"✓ wrote {len(data)} family redirect(s) → {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
