"""Memory-side adapter for wiki control surfaces.

New wiki semantics live in the portable Rust core and are reached through
``WikiCoreClient``. Older Python authoring helpers are transitional record
writers for proposal/decision receipts that the Rust core does not yet own.
"""

from .core_client import (
    WikiCoreClient,
    WikiCoreError,
    resolve_wiki_core_binary,
    wiki_agent_heartbeat,
    wiki_agent_identify,
    wiki_agent_inbox,
    wiki_agent_retire,
    wiki_agent_status,
    wiki_agent_status_by_thread,
    wiki_asset_add,
    wiki_asset_list,
    wiki_ensure,
    wiki_list,
    wiki_mail_claim,
    wiki_mail_mark,
    wiki_mail_open,
    wiki_mail_record_injection,
    wiki_mail_send,
    wiki_mail_snooze,
    wiki_notify_ack,
    wiki_notify_dispatch,
    wiki_notify_poll,
    wiki_page_create_all,
    wiki_page_create,
    wiki_page_delete,
    wiki_page_open,
    wiki_page_patch_body,
    wiki_page_restore,
    wiki_page_status,
    wiki_page_write_body,
    wiki_publish,
    wiki_publish_status,
    wiki_reference_list,
    wiki_status,
    wiki_talk_append,
    wiki_validate,
)

__all__ = [
    "WikiCoreClient",
    "WikiCoreError",
    "resolve_wiki_core_binary",
    "wiki_agent_heartbeat",
    "wiki_agent_identify",
    "wiki_agent_inbox",
    "wiki_agent_retire",
    "wiki_agent_status",
    "wiki_agent_status_by_thread",
    "wiki_asset_add",
    "wiki_asset_list",
    "wiki_ensure",
    "wiki_list",
    "wiki_mail_claim",
    "wiki_mail_mark",
    "wiki_mail_open",
    "wiki_mail_record_injection",
    "wiki_mail_send",
    "wiki_mail_snooze",
    "wiki_notify_ack",
    "wiki_notify_dispatch",
    "wiki_notify_poll",
    "wiki_page_create_all",
    "wiki_page_create",
    "wiki_page_delete",
    "wiki_page_open",
    "wiki_page_patch_body",
    "wiki_page_restore",
    "wiki_page_status",
    "wiki_page_write_body",
    "wiki_publish",
    "wiki_publish_status",
    "wiki_reference_list",
    "wiki_status",
    "wiki_talk_append",
    "wiki_validate",
]
